import pygame

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3
SHOW_MINES = 4

GREEN=(0,115,3)
BLACK = (0, 0, 0)
GRID_LINE_COLOR=(20, 60, 20)
MINE_FILL_COLOR=(160, 160, 160)
MINE_BORDER_COLOR=(60, 60, 60)

SPACE_BETWEEN_ITEMS = 20

FONT_NAME = "Calibri"

WELCOME_MESSAGE = "welcome To The Flag Game. Have Fun!"
LOSE_MESSAGE = "You Lost"
WIN_MESSAGE = "You Won"

WELCOME_MESSAGE_POS = (SPACE_BETWEEN_ITEMS * 3, SPACE_BETWEEN_ITEMS)
LOSE_WIN_MESSAGE_POS = (SPACE_BETWEEN_ITEMS * 20, SPACE_BETWEEN_ITEMS * 10)

WIN_LOSE_MESSAGE_SIZE = 60
WELCOME_MESSAGE_SIZE = 20


GRID_COLS = 50
GRID_ROWS = 25

PLAYER_ITEM_HEIGHT = 4
PLAYER_ITEM_WIDTH = 2
FLAG_ITEM_HEIGHT = 3
FLAG_ITEM_WIDTH = 4

SOLDIER_SIZE = (PLAYER_ITEM_WIDTH * SPACE_BETWEEN_ITEMS * 1.5, PLAYER_ITEM_HEIGHT * SPACE_BETWEEN_ITEMS)
FLAG_SIZE=(FLAG_ITEM_WIDTH * SPACE_BETWEEN_ITEMS, FLAG_ITEM_HEIGHT * SPACE_BETWEEN_ITEMS)

MINE_PERCENTAGE = 2

GRASS_SIZE=(SPACE_BETWEEN_ITEMS*3,SPACE_BETWEEN_ITEMS*3)
GRASS_NUMBER=20

MINE_SIZE = (SPACE_BETWEEN_ITEMS * 3, SPACE_BETWEEN_ITEMS)

WINDOW_WIDTH= GRID_COLS*SPACE_BETWEEN_ITEMS
WINDOW_HEIGHT= GRID_ROWS*SPACE_BETWEEN_ITEMS

MINE_COUNT=20
MINE_LINE=3

KEYS_DICT = {
    pygame.K_1: 1,
    pygame.K_2: 2,
    pygame.K_3: 3,
    pygame.K_4: 4,
    pygame.K_5: 5,
    pygame.K_6: 6,
    pygame.K_7: 7,
    pygame.K_8: 8,
    pygame.K_9: 9
}

TRAP_COUNT = 5
