
RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3
SHOW_MINES = 4

GREEN=(0,115,3)

SPACE_BETWEEN_ITEMS = 20
GRID_COLS = 50
GRID_ROWS = 25

PLAYER_ITEM_HEIGHT = 4
PLAYER_ITEM_WIDTH = 2
FLAG_ITEM_HEIGHT = 3
FLAG_ITEM_WIDTH = 4

MINE_PERCENTAGE = 5

GRASS_SIZE=(SPACE_BETWEEN_ITEMS*3,SPACE_BETWEEN_ITEMS*3)
GRASS_NUMBER=20

WINDOW_WIDTH= GRID_COLS*SPACE_BETWEEN_ITEMS
WINDOW_HEIGHT= GRID_ROWS*SPACE_BETWEEN_ITEMS

MINE_COUNT=20
MINE_LINE=3


